#!/usr/bin/env bash

set -euo pipefail

DIFF_SCHEMES="COLLOC_GL2 COLLOC_GL4 COLLOC_GL6 MAGNUS_GL2 MAGNUS_GL4 MAGNUS_GL6"
MATRIX_TYPES="BAND BLOCK"

# for DIFF_SCHEME in $DIFF_SCHEMES; do
#   for MATRIX_TYPE in $MATRIX_TYPES; do
#     RUN_NAME="${DIFF_SCHEME}_${MATRIX_TYPE}"
#     mkdir -p test-data/generated/$RUN_NAME
#     sed test-data/gyre-inlist-template \
#       -e "s/@DIFF_SCHEME@/$DIFF_SCHEME/" \
#       -e "s/@MATRIX_TYPE@/$MATRIX_TYPE/" > test-data/generated/$RUN_NAME/inlist
#     hyperfine --export-json=test-data/generated/$RUN_NAME.json -- \
#       "pushd test-data/generated/$RUN_NAME; OMP_NUM_THREADS=1 gyre inlist; popd"
#   done
# done

cargo build --release

DIFF_SCHEMES_STORM="colloc2 colloc4 magnus2 magnus4 magnus6 magnus8"
for DIFF_SCHEME in $DIFF_SCHEMES_STORM; do
    RUN_NAME="${DIFF_SCHEME}_storm"
    mkdir -p test-data/generated/$RUN_NAME
    cat >test-data/generated/$RUN_NAME/input <<EOF
input test-data/test-model-tams.GSM
scan 0 0 1 25 25 --difference-scheme $DIFF_SCHEME
output --properties=frequency test-data/generated/$RUN_NAME/summary.hdf5
EOF
    hyperfine --export-json=test-data/generated/$RUN_NAME.json -- \
      "./target/release/storm  test-data/generated/$RUN_NAME/input"
done
