contentDir = 'content'
enableEmoji = true

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false
    [[module.imports]]
        path = "github.com/hugomods/icons/vendors/bootstrap"
        disable = false

[markup]
    [markup.tableOfContents]
      endLevel = 3
      startLevel = 1
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
      block = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

[params.docs]
    darkMode = true
    themeColor = "cardinal"
    sidebarIcons = true
    descriptions = true
    logoLinkURL = "/preview/docs"
    extLinkNewTab = false

[params]
    sans_serif_font = "system-ui, sans-serif"
    secondary_font = "system-ui, sans-serif"
    math = true
