name: Deploy docs

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.147.1
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cd docs && hugo --gc --minify --baseURL "https://stellar-oscillations.org/preview/"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./docs/public
  deploy:
    needs: build
    environment:
      name: stellar-oscillations.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: site
          path: ./docs/public
      - name: Set SSH key
        run: echo "$SSH_KEY" > key && chmod 600 key
        env:
          SSH_KEY: ${{secrets.MAIN_SITE_KEY}}
      - name: Set known hosts
        run: mkdir -p ~/.ssh/ && echo "stellar-oscillations.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKlufAT5tJFqccQsQdT2yHnJZC75MrCZzJ08Wez+x8iy" >> ~/.ssh/known_hosts
      - name: Copy files
        run: rsync -e "ssh -i key" --delete-after -vrl docs/public/ oscillations@stellar-oscillations.org:preview

